### ISSUE TITLE
Message.TRACK_LINKS enum 

### ISSUE THREAD

**Issue by twersinger** [wildbit/postmark-java#1]
When setTrackLinks 
Message.TRACK_LINKS enum has 'text', 'Html' and 'HtmlAndText'
Postmark exception: 
The value for 'TrackLinks' is not valid. Valid options are: null, 'None', 'HtmlAndText', 'HtmlOnly', 'TextOnly'

**Comment by ibalosh** [comment]
Hi

thank you for reporting this issue. We patched it and released an update for it.

With version 1.0.2 of library the issue should be gone.

Igor
