### ISSUE TITLE
Unsupported Date format

### ISSUE THREAD

**Issue by yholkamp** [wildbit/postmark-java#14]
Using version 1.2.0 with Jackson 2.9.8 I was unable to decode an inbound webhook received from Postmark due to the date format that was used.

The webhook contained the following; 

    "Date": "26 May 2019 10:39:51 -0400",

which resulted in the following error;

    com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot parse date "26 May 2019 10:39:51 -0400": not compatible with any of standard forms ("yyyy-MM-dd'T'HH:mm:ss.SSSZ", "yyyy-MM-dd'T'HH:mm:ss.SSS", "EEE, dd MMM yyyy HH:mm:ss zzz", "yyyy-MM-dd"))

Could this format be added as an alias?

**Comment by ibalosh** [comment]
Hi @yholkamp 

I will see to check out the issue this week

**Comment by ibalosh** [comment]
Hi @yholkamp 

this issue should be resolved now. Let me know if you still see it in version 1.2.1?

Igor
