### ISSUE TITLE
Some methods were not updated to handle the new JSON error code & error message responses

### ISSUE THREAD

**Issue by logantracyo** [wildbit/postmark-java#22]
One specific example:

```
    public String retryFailedInboundMessage(String id) throws PostmarkException, IOException {
        String response = execute(HttpClient.REQUEST_TYPES.PUT, getEndpointUrl(inboundMessagesEndpoint + id + "/retry"));
        return dataHandler.fromJson(response, String.class);
    }

```
Calling this method with a valid / retriable message ID results in a Jackson exception because `response` is now a JSON-encoded Object, not just a String value.  It seems sane to keep the return type as `String`, by decoding the JSON response to `BaseMessageResponse.class` and returning the String value.

`bypassInboundMessage()` also should be updated -- and some of the other methods that return a generic HashMap seem like also using the BaseMessageResponse there might be a better choice (since they're also getting the Integer ErrorCode, String Message response) -- in which case returning `BaseMessageResponse` rather than `BaseMessageResponse.getMessage()` might be best.

I've added a PR, #21, in case that's of any help.

**Comment by ibalosh** [comment]
Hi,

we just released new version 1.5.5 which should be available by maven in couple of minutes, which resolves this issue and adds new endpoints to the library.

Let us know if it works ok for you.
