### ISSUE TITLE
Java 9: Illegal reflective access warning caused by JAXB dependency

### ISSUE THREAD

**Issue by liorhar** [wildbit/postmark-java#23]
When using postmark's lib with java version greater than 8 there's a warning about illegal access caused by the jaxb dependency.
See here - https://github.com/javaee/jaxb-v2/issues/1197

Upgrading from version 2.3.0 to 2.3.1 should resolve that issue. 
Btw, does postmark use jaxb at all? I excluded it from my dependencies and everything seems to work fine

**Comment by ibalosh** [comment]
Hi @liorhar 

could you share details which version of Java are you using? [Jersey requires those dependencies](https://github.com/dropwizard/dropwizard/issues/2318) and can cause issues on newer java versions when removed.

Igor

**Comment by liorhar** [comment]
I'm using java 13 (adopt openjdk) I believe the issue is with every version greater than 8

**Comment by liorhar** [comment]
yeah, it looks good now, thanks 🙏

**Comment by ibalosh** [comment]
Hey, glad it works now ok, thank you for letting us know
