### ISSUE TITLE
log4j2.properties overriding log4j2 configuration

### ISSUE THREAD

**Issue by DarkNormal** [wildbit/postmark-java#26]
Hi, I'm trying to use the postmark-java dependency and all seems well except for our current logging configuration seems to be getting overridden by the log4j2.properties file from the postmark-java library.

I'm not sure if this properties file should be included in the jar or not - from reading online it's usually warned against for this exact reason.

My current log4j2 configuration is through log4j2.xml, while debugging the application I can see that without the postmark-java dependency my configuration looks like below (XmlConfiguration, level shown as DEBUG):
![image](https://user-images.githubusercontent.com/4855895/119803253-2f8dcb80-bed7-11eb-9c0b-6dc403d71a2e.png)

While with the dependency added, the logger is now using values from log4j2.properties (Note the difference here, originally the config was XmlConfiguration, it's now PropertiesConfiguration, also level is now OFF), and no longer logging anything
![image](https://user-images.githubusercontent.com/4855895/119802944-e8073f80-bed6-11eb-8acb-79583766fa19.png)

**Comment by ibalosh** [comment]
Hi @DarkNormal 

this issue should be resolved in latest 1.7.2 version.

Igor
