### ISSUE TITLE
Feature Request - support custom jackson object mapper

### ISSUE THREAD

**Issue by liorhar** [wildbit/postmark-java#29]
It would be useful if the object mapper used to serialize the template parameters was customizable.
For example, the built-in object mapper uses `PropertyNamingStrategy.UPPER_CAMEL_CASE` while we prefer `LOWER_CAMEL_CASE`
Also, we're using Kotlin so registering the kotlin module would be very useful

**Comment by ibalosh** [comment]
Hi @liorhar 

could you share bit more details on where do you use this and in which scenario? Are you referring to template model, when sending emails with templates?

Thanks

**Comment by valh1996** [comment]
Hi @ibalosh 
I'm trying to send a List of DTO through `setTemplateModel()`:
```java
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class PeriodData {
    public LocalDate start;
    public LocalDate end;
}
```
```java
List<PeriodData> periods = this.periodService.getPeriods(contract);
HashMap<String, Object> model = new HashMap<>() {{
    put("periods", periods);
   //
}};

TemplatedMessage message = new TemplatedMessage(senderAddress, recipient);
message.setMessageStream("outbound");
message.setTemplateId(templateId);
message.setTemplateModel(model);
postmarkClient.deliverMessageWithTemplate(message);
```

However, I encounter the following error:
```
Java 8 date/time type `java.time.LocalDate` not supported by default
```

The ObjectMapper defined [here](https://github.com/ActiveCampaign/postmark-java/blob/main/src/main/java/com/postmarkapp/postmark/client/data/parser/DataHandler.java#L18-L20) does not seem to have the Java Time module configured. Is there a fix please?

**Comment by ibalosh** [comment]
Hi @valh1996 

Sorry for the late response. At the moment, we suggest transforming the model for specific objects, just the way you did in the workaround. If you would like to file a feature request that we could add in future, please create a separate feature request.
