### ISSUE TITLE
HeaderValueException:Too many "Content-Type" header values: "[application/json, application/json]"

### ISSUE THREAD

**Issue by aonurozcan** [wildbit/postmark-java#36]
As discussed in this issue https://github.com/wildbit/postmark-java/issues/33

We're still getting this error time to time. We're using 1.8.0 version.

Do you have any idea on this?
Thank you

**Comment by ibalosh** [comment]
duplicate #33

**Comment by ibalosh** [comment]
will see to investiage further #33 this week
