### ISSUE TITLE
Why attachments need to be files paths (String) ?

### ISSUE THREAD

**Issue by jflebeau** [wildbit/postmark-java#7]
This mean that creating attachments on the fly hard for nothing (IMHO).

**Comment by ibalosh** [comment]
Hi,

thank you for contacting us back regarding the library. The main reason behind that is avoiding mistakes when doing attachments creation on the fly. Its much easier to make sure attachment is correct by having it in the file, and allowing the library to read, encode and send it for you.

We can add overload method for adding attachments on fly too. Could you share example on how you plan to add attachments on the fly, so we have better idea on whether its a good fit to add to the model?

**Comment by ibalosh** [comment]
Hey @jflebeau 

Got it, I will be doing some updates to library this week. Will tackle adding attachments on the fly too.

**Comment by ibalosh** [comment]
Hi @jflebeau 

I was checking out today the model for messages and you can actually attach attachments on fly.
There is support for it.

Check out the following example:

```
Message message = new Message("igor+from@test.com", "john@test.com", "Subject", "Body");

String test = "test message line 1\ntest message line 2";
        
HashMap<String,String> attachment = new HashMap<>();
attachment.put("Name", "filename.txt");
attachment.put("Content", Base64.getEncoder().encodeToString(test.getBytes()));
attachment.put("ContentType", "text");
message.addAttachment(attachment);
```
I will add though additional helpers and update documentation to make it clearer. Many thanks on catching that and using the library!
and then send the message.

**Comment by ibalosh** [comment]
Hi @jflebeau 

the library has been updated. You should be able to easily attach content on the fly with couple of new options. Check out the wiki for details:

https://github.com/wildbit/postmark-java/wiki/Email-sending

**Comment by jflebeau** [comment]
Not on `TemplateMessage`.

**Comment by ibalosh** [comment]
oops, you are right, added it for regular messages only. Updated TemplatedMessage model too, should be up in less than an hour.
